#!/bin/sh

export REFIT_VERSION="BETA-0.11"

docker-compose up -d cassandra refit-pulsar-standalone minio

echo "Wait for core services to bootstrap"
sleep 30

docker-compose up -d

unset REFIT_VERSION


echo "========================== REFIT Started =================================="
echo "Watch the notebook logs to get your Jupyter Notebook URL, Run the following"
echo "docker-compose logs -f notebook"
