#!/bin/sh

export REFIT_VERSION="BETA-0.9"

docker-compose up -d cassandra refit-pulsar-standalone minio

echo "Wait for core services to bootstrap"
sleep 30

docker-compose up -d

unset REFIT_VERSION